plugins {
    id 'idea'
    id "io.github.0ffz.github-packages" version "1.2.1"
}

ext.jmonkeyengineVersion = '3.8.1-stable'

allprojects {
    repositories {
        google()
        maven { url "https://jitpack.io" }
        mavenCentral()
        mavenLocal()
    }
}

subprojects {
    apply plugin: 'idea'
    
    configurations.all {
        resolutionStrategy.force(
                "org.jmonkeyengine:jme3-core:$jmonkeyengineVersion"
        )
        exclude group: "org.jmonkeyengine", module: "jme3-lwjgl"
    }
}

task buildAllDistributions {
    group 'distribution'
    dependsOn ':desktop:zipWindowsDistribution'
    dependsOn ':desktop:zipLinuxDistribution'
    dependsOn ':desktop:zipMacDistribution'
}